"""make_task_id_nullable

Revision ID: da1a6b1632f1
Revises: 887fdc31fa31
Create Date: 2026-04-29 05:37:59.068443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1a6b1632f1'
down_revision: Union[str, Sequence[str], None] = '887fdc31fa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
