"""initial schema

Revision ID: 887fdc31fa31
Revises: 
Create Date: 2026-04-28 15:41:22.856663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887fdc31fa31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_tokens',
    sa.Column('github_user_id', sa.Text(), nullable=False),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.Text(), server_default='bearer', nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('github_user_id')
    )
    op.create_table('guilds',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('github_user_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('from_agent', sa.Text(), nullable=True),
    sa.Column('to_agent', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('github_user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['github_user_id'], ['github_tokens.github_user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('workers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('repos', sa.Text(), server_default='[]', nullable=False),
    sa.Column('state', sa.Text(), server_default='idle', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default='worker', nullable=False),
    sa.Column('state', sa.Text(), server_default='idle', nullable=False),
    sa.Column('joined_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), server_default='claude', nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('issue_repo', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), server_default='pending', nullable=False),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('worktree_path', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.Text(), nullable=True),
    sa.Column('phase', sa.Text(), server_default='execute', nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs')
    op.drop_table('tasks')
    op.drop_table('agents')
    op.drop_table('workers')
    op.drop_table('user_sessions')
    op.drop_table('messages')
    op.drop_table('guilds')
    op.drop_table('github_tokens')
    # ### end Alembic commands ###
